In [1]:
import pandas as pd 
import seaborn as sns
import numpy as np

In [2]:
data = pd.read_csv ("/home/moalziab/group02/resources/felixstowe_rotterdam/felixstowe_rotterdam_cleaned.csv")

In [3]:
data.head()

,EndLatitude,EndLongitude,Latitude,Longitude,EndTime,time,shiptype,SOG,mean_dir_sin,mean_dir_cos,mean_size,time_remaining
0,51.9,4.36,51.95,1.31,1.453397e+09,1.453366e+09,79.0,1.2,-0.983255,0.182236,76.226667,30600.0
1,51.9,4.36,51.95,1.31,1.453397e+09,1.453366e+09,79.0,2.3,-0.945519,0.325568,76.226667,30540.0
2,51.9,4.36,51.95,1.30,1.453397e+09,1.453366e+09,79.0,4.6,-0.999848,0.017452,76.226667,30480.0
3,51.9,4.36,51.95,1.30,1.453397e+09,1.453366e+09,79.0,3.7,-0.814116,-0.580703,76.226667,30420.0
4,51.9,4.36,51.95,1.30,1.453397e+09,1.453366e+09,79.0,3.8,-0.258819,-0.965926,76.226667,30360.0

In [4]:
data.tail()

,EndLatitude,EndLongitude,Latitude,Longitude,EndTime,time,shiptype,SOG,mean_dir_sin,mean_dir_cos,mean_size,time_remaining
427004,51.95,3.99,51.96,4.04,1.475278e+09,1.475274e+09,71.0,6.5,-0.935135,0.354291,155.2,3660.0
427005,51.95,3.99,51.96,3.99,1.475278e+09,1.475276e+09,71.0,4.5,0.096714,-0.995312,155.2,2040.0
427006,51.95,3.99,51.95,3.99,1.475278e+09,1.475277e+09,71.0,0.9,-0.284852,-0.958572,155.2,840.0
427007,51.95,3.99,51.95,3.99,1.475278e+09,1.475277e+09,71.0,0.8,-0.297375,-0.954761,155.2,720.0
427008,51.95,3.99,51.99,3.76,1.475278e+09,1.475268e+09,71.0,4.4,0.942057,-0.335452,155.2,9780.0

In [5]:
data.columns

Index(['EndLatitude', 'EndLongitude', 'Latitude', 'Longitude', 'EndTime',
       'time', 'shiptype', 'SOG', 'mean_dir_sin', 'mean_dir_cos', 'mean_size',
       'time_remaining'],
      dtype='object')

In [6]:
data.shape

(427009, 12)

In [7]:
data.describe()

,EndLatitude,EndLongitude,Latitude,Longitude,EndTime,time,shiptype,SOG,mean_dir_sin,mean_dir_cos,mean_size,time_remaining
count,427009.000000,427009.000000,427009.000000,427009.000000,4.270090e+05,4.270090e+05,427009.000000,427009.000000,427009.000000,427009.000000,427009.000000,427009.00000
mean,51.912918,4.270478,51.947846,2.815857,1.468312e+09,1.468296e+09,74.250683,12.856317,0.795339,-0.068338,74.521678,16618.48050
std,0.035468,0.139774,0.054692,1.145321,1.147133e+07,1.147184e+07,4.303623,4.692990,0.438441,0.412960,22.553831,11782.96138
min,51.680000,3.890000,50.930000,1.080000,1.452708e+09,1.452675e+09,70.000000,0.200000,-1.000000,-1.000000,1.633333,0.00000
25%,51.900000,4.120000,51.920000,1.680000,1.458717e+09,1.458710e+09,70.000000,10.400000,0.857616,-0.308187,59.623333,5340.00000
50%,51.900000,4.360000,51.950000,2.700000,1.466578e+09,1.466567e+09,71.000000,13.800000,0.970506,-0.043619,76.233333,17280.00000
75%,51.940000,4.360000,51.990000,3.990000,1.474294e+09,1.474263e+09,79.000000,15.900000,0.990983,0.190809,76.533333,26340.00000
max,51.990000,4.630000,52.320000,4.630000,1.494185e+09,1.494185e+09,79.000000,76.800000,1.000000,0.999848,157.573333,53940.00000

In [9]:
data.isnull().sum()

EndLatitude       0
EndLongitude      0
Latitude          0
Longitude         0
EndTime           0
time              0
shiptype          0
SOG               0
mean_dir_sin      0
mean_dir_cos      0
mean_size         0
time_remaining    0
dtype: int64

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler